[package]
name = "deploy-helper"
version.workspace = true
edition.workspace = true

[dependencies]
search-common = { path = "../../crates/search-common" }
ciborium = "0.2"
serde = { workspace = true }
ed25519-dalek = { workspace = true, features = ["rand_core"] }
rand = "0.8"
bs58 = "0.5"
